const fs=require('fs'),vm=require('vm'),a=require('assert/strict');const src=fs.readFileSync(require('node:path').join(__dirname,'../dist/app.js'),'utf8');const {allocate,apply78Rule,splitSide}=require('../dist/app.js');let assertions=0;function eq(x,y){a.deepEqual(x,y);assertions++;}function ok(x){a.ok(x);assertions++;}const els=new Map(),extraNodes=Array.from({length:9},(_,i)=>({dataset:{extra:String(i)},checked:false})),freeNodes=extraNodes.map(()=>({checked:false,disabled:true}));function get(id){if(!els.has(id))els.set(id,{value:'',checked:false,selectedOptions:[{text:'濃湯'}]});return els.get(id)}get('soup').value='0';get('shareCount').value='1';const ctx={document:{getElementById:get,querySelectorAll:q=>q==='[data-extra]:checked'?extraNodes.filter(x=>x.checked):q==='[data-extra]'?extraNodes:q==='[data-free-extra]'?freeNodes:[],querySelector:q=>freeNodes[Number(q.match(/"(\d+)"/)[1])]}};vm.createContext(ctx);vm.runInContext(src.replace('renderMenu();render();',`renderMenu();render();globalThis.api={draft,render,renderMenu,choose(c,i=0){category=c;selected=i;renderMenu();},orders:()=>orders,setOrders(a){orders=a;render();},catalog,extras};`),ctx);const api=ctx.api;
for(const [cat,items] of Object.entries(api.catalog)){for(let i=0;i<items.length;i++){api.choose(cat,i);eq(api.draft().price,items[i][1]*100);get('free').checked=true;eq(api.draft().price,0);get('free').checked=false;get('fixed').checked=true;eq(api.draft().fixed,true);get('fixed').checked=false;}}
api.choose('拉麵');for(let i=0;i<9;i++){extraNodes[i].checked=true;eq(api.draft().price,7800+api.extras[i][1]*100);freeNodes[i].checked=true;eq(api.draft().price,7800);extraNodes[i].checked=false;freeNodes[i].checked=false;}
extraNodes.forEach(x=>x.checked=true);eq(api.draft().price,20300);extraNodes.forEach(x=>x.checked=false);get('noEgg').checked=true;eq(api.draft().price,6800);get('noEgg').checked=false;get('noOnion').checked=true;get('noBamboo').checked=true;ok(api.draft().name.includes('走蔥、走筍'));get('noOnion').checked=false;get('noBamboo').checked=false;
get('soup').value='custom';get('soupCustom').value='20';eq(api.draft().price,9800);get('soupCustom').value='-1';a.throws(()=>api.draft());get('soup').value='0';api.choose('限定／自訂');get('customName').value='<test>';get('customPrice').value='78';get('customRamen').checked=true;eq(api.draft().isRamen,true);get('customRamen').checked=false;eq(api.draft().isRamen,false);for(const p of ['', '-1','1.001','NaN','1000001']){get('customPrice').value=p;a.throws(()=>api.draft());assertions++;}get('free').checked=true;eq(api.draft().price,0);get('free').checked=false;
const nine=[120,112,78,113,90,105,120,108,90].map((p,i)=>({name:'麵'+i,person:'人'+i,price:p*100,isRamen:true,fixed:[1,4,5].includes(i)}));eq(allocate(nine,61800),[5933,11200,3857,5587,9000,10500,5933,5340,4450]);eq(allocate(apply78Rule(nine,true),61800),[5075,11200,7800,4778,9000,10500,5074,4567,3806]);eq(nine[2].fixed,false);eq(apply78Rule([{price:7800,isRamen:false}],true)[0].fixed,false);for(const [items,paid] of [[[],0],[nine,1],[[{price:100,fixed:true}],101],[[{price:0}],1],[nine,-1],[nine,1.5]]){a.throws(()=>allocate(items,paid));assertions++;}eq(allocate([{price:0}],0),[0]);eq(allocate([{price:100,fixed:true}],100),[100]);
for(const n of [1,2,3,50]){const p=splitSide({price:3500,name:'餃子'},n,Array.from({length:n},(_,i)=>'人'+i));eq(p.reduce((s,x)=>s+x.price,0),3500);eq(p.length,n);}for(const [n,names] of [[0,[]],[51,[]],[1.5,[]],[2,['甲']],[2,['甲','甲']],[2,['甲',' ']]]){a.throws(()=>splitSide({price:3500},n,names));assertions++;}
let seed=17;function rand(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/2**32;}for(let t=0;t<1000;t++){const it=Array.from({length:10},()=>({price:Math.floor(rand()*10000),fixed:rand()<.3}));it[0].fixed=false;it[0].price=100;const total=it.filter(x=>x.fixed).reduce((s,x)=>s+x.price,0)+Math.floor(rand()*100000);const out=allocate(it,total);eq(out.reduce((s,x)=>s+x,0),total);ok(out.every((x,i)=>x>=0&&Number.isInteger(x)&&(!it[i].fixed||x===it[i].price)));}
get('paid').value='618';api.setOrders(nine);ok(get('results').innerHTML.includes('分攤 19.08%'));get('exclude78').checked=true;api.render();ok(get('results').innerHTML.includes('分攤 21.78%'));api.setOrders([{name:'<img onerror=x>',person:'<name>',price:1000},{name:'小食',person:'<name>',price:1000}]);get('paid').value='20';api.render();ok(get('results').innerHTML.includes('&lt;img onerror=x&gt;'));ok(!get('results').innerHTML.includes('<img onerror=x>'));
console.log(JSON.stringify({assertions,randomCases:1000,status:'PASS'}));
